using System;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Gnosis.ShaderGenerator;

[Generator]
public sealed class GnosisShaderSourceGenerator : ISourceGenerator
{
    private static readonly DiagnosticDescriptor ShaderCompileError = new(
        id: "GGS0001",
        title: "Shader compile error",
        messageFormat: "Failed to compile shader file '{0}': {1}",
        category: "ShaderCompiler",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var shaderFiles = context.AdditionalFiles
            .Where(f => f.Path.EndsWith(".ggs", StringComparison.OrdinalIgnoreCase))
            .ToList();

        if (shaderFiles.Count == 0)
        {
            return;
        }

        foreach (var shaderFile in shaderFiles)
        {
            ProcessShaderFile(context, shaderFile);
        }
    }

    private void ProcessShaderFile(GeneratorExecutionContext context, AdditionalText shaderFile)
    {
        var sourceText = shaderFile.GetText(context.CancellationToken);
        if (sourceText == null)
        {
            return;
        }

        var fileName = Path.GetFileNameWithoutExtension(shaderFile.Path);
        var className = ToPascalCase(fileName);

        try
        {
            var source = sourceText.ToString();
            var bytecodePlaceholder = GeneratePlaceholderBytecode(source);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine($"namespace Gnosis.Shader.Generated;");
            sb.AppendLine();
            sb.AppendLine($"public static partial class {className}Shader");
            sb.AppendLine("{");
            sb.AppendLine($"    public static ReadOnlySpan<byte> Bytecode => new byte[] {{ {FormatByteArray(bytecodePlaceholder)} }};");
            sb.AppendLine("}");

            context.AddSource($"{className}Shader.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                ShaderCompileError,
                Location.None,
                shaderFile.Path,
                ex.Message));
        }
    }

    private static byte[] GeneratePlaceholderBytecode(string source)
    {
        var header = new uint[]
        {
            0x07230203,
            0x00010500,
            0x00470000,
            5,
            0
        };

        var result = new byte[header.Length * 4];
        Buffer.BlockCopy(header, 0, result, 0, header.Length * 4);
        return result;
    }

    private static string FormatByteArray(byte[] data)
    {
        if (data.Length == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        for (int i = 0; i < data.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            if (i % 16 == 0 && i > 0)
            {
                sb.AppendLine();
                sb.Append("        ");
            }

            sb.Append($"0x{data[i]:X2}");
        }
        return sb.ToString();
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return "Shader";
        }

        var parts = name.Split(new[] { '_', '-', '.' }, StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length > 0)
            {
                sb.Append(char.ToUpperInvariant(part[0]));
                sb.Append(part.Substring(1).ToLowerInvariant());
            }
        }
        return sb.ToString();
    }
}
