<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <PackageId>Gnosis.Tests</PackageId>
        <RootNamespace>Gnosis</RootNamespace>
        <Description>Gnosis 引擎实际测试用例</Description>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0"/>
        <PackageReference Include="NUnit" Version="4.0.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0"/>
        <PackageReference Include="NUnit.Analyzers" Version="4.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\projects\Gnosis.Core\Gnosis.Core.csproj"/>
        <ProjectReference Include="..\..\projects\Gnosis.ECS\Gnosis.ECS.csproj"/>
        <ProjectReference Include="..\..\projects\Gnosis.IR\Gnosis.IR.csproj"/>
        <ProjectReference Include="..\..\projects\Gnosis.Runtime\Gnosis.Runtime.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Network\**\*.cs"/>
        <Compile Remove="Compiler\**\*.cs"/>
        <Compile Remove="ECS\**\*.cs"/>
        <Compile Remove="Core\**\*.cs"/>
        <Compile Remove="Assets\**\*.cs"/>
        <Compile Remove="Infrastructure\**\*.cs"/>
        <Compile Remove="Database\**\*.cs"/>
    </ItemGroup>

</Project>
