using System.Text;
using Gnosis.Compiler.Diagnostics;
using Gnosis.Compiler.ShaderFrontend;
using Gnosis.Rendering.ShaderCompiler.Frontend;

namespace Gnosis.Rendering.ShaderGenerator;

[Generator]
public sealed class GnosisShaderSourceGenerator : ISourceGenerator
{
    #region 字段

    private static readonly DiagnosticDescriptor ShaderCompileError = new(
        id: "GGS0001",
        title: "着色器编译错误",
        messageFormat: "编译着色器文件 '{0}' 失败：{1}",
        category: "ShaderCompiler",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    #endregion

    #region ISourceGenerator 实现

    /// <summary>
    /// 初始化源生成器
    /// </summary>
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    /// <summary>
    /// 执行源生成，扫描 .ggs 文件并将 GGShader 编译为 SPIR-V 字节码，再生成 C# 包装代码
    /// </summary>
    public void Execute(GeneratorExecutionContext context)
    {
        var shaderFiles = context.AdditionalFiles
            .Where(f => f.Path.EndsWith(".ggs", StringComparison.OrdinalIgnoreCase))
            .ToList();

        if (shaderFiles.Count == 0)
        {
            return;
        }

        foreach (var shaderFile in shaderFiles)
        {
            ProcessShaderFile(context, shaderFile);
        }
    }

    #endregion

    #region 着色器处理

    /// <summary>
    /// 处理单个 GGShader 着色器文件，编译为 SPIR-V 字节码并生成 C# 包装类
    /// <para>注意：GGShader 是独立的游戏着色器语言，此处生成的 C# 包装类仅作为引擎侧承载 SPIR-V 字节码的方式。</para>
    /// </summary>
    private void ProcessShaderFile(GeneratorExecutionContext context, AdditionalText shaderFile)
    {
        var sourceText = shaderFile.GetText(context.CancellationToken);
        if (sourceText == null)
        {
            return;
        }

        var fileName = Path.GetFileNameWithoutExtension(shaderFile.Path);
        var className = ToPascalCase(fileName);

        try
        {
            var source = sourceText.ToString();
            var bytecode = CompileShaderToSpirV(source);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine($"namespace Gnosis.Shader.Generated;");
            sb.AppendLine();
            sb.AppendLine($"public static partial class {className}Shader");
            sb.AppendLine("{");
            sb.AppendLine($"    public static ReadOnlySpan<byte> Bytecode => new byte[] {{ {FormatByteArray(bytecode)} }};");
            sb.AppendLine("}");

            context.AddSource($"{className}Shader.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
        catch (ShaderCompilationException ex)
        {
            foreach (var error in ex.Errors)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ShaderCompileError,
                    Location.None,
                    shaderFile.Path,
                    error.Message));
            }
        }
        catch (InvalidOperationException ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                ShaderCompileError,
                Location.None,
                shaderFile.Path,
                ex.Message));
        }
    }

    #endregion

    #region 编译方法

    /// <summary>
    /// 使用 ShaderCompiler 将 GGShader 着色器源码编译为 SPIR-V 字节码
    /// </summary>
    private static byte[] CompileShaderToSpirV(string source)
    {
        var diagnostics = new DiagnosticSink();
        var compiler = new GgShaderCompiler(diagnostics);
        return compiler.CompileToSpirV(source);
    }

    #endregion

    #region 辅助方法

    /// <summary>
    /// 将字节数组格式化为 C# 数组初始化器字符串
    /// </summary>
    private static string FormatByteArray(byte[] data)
    {
        if (data.Length == 0)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        for (int i = 0; i < data.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            if (i % 16 == 0 && i > 0)
            {
                sb.AppendLine();
                sb.Append("        ");
            }

            sb.Append($"0x{data[i]:X2}");
        }
        return sb.ToString();
    }

    /// <summary>
    /// 将文件名转换为 PascalCase 命名格式
    /// </summary>
    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return "Shader";
        }

        var parts = name.Split(['_', '-', '.'], StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            if (part.Length > 0)
            {
                sb.Append(char.ToUpperInvariant(part[0]));
                sb.Append(part.Substring(1).ToLowerInvariant());
            }
        }
        return sb.ToString();
    }

    #endregion
}
